version: '2'
services:
  seed:
    image: shardexample/akkashardingexample:0.1
    ports:
      - '1600:1600'
      - '9000:9000'
    environment:
      CLUSTER_PORT: 1600
      CLUSTER_IP: seed
      SEED_PORT_1600_TCP_ADDR: seed
      CLUSTER_ROLE: seed
  w1:
    image: shardexample/akkashardingexample:0.1
    ports:
      - '1601:1601'
      - '9001:9000'
    environment:
      CLUSTER_PORT: 1601
      CLUSTER_IP: w1
      SEED_PORT_1600_TCP_ADDR: seed
      CLUSTER_ROLE: worker